[project]
name = "revo3-examples"
version = "2.0.0rc9"
description = "BrainCo Revo3 SDK Python Examples"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "bc-revo3-sdk>=2.0.0rc9,<3",
    "colorlog>=6.9.0",
    "pyserial>=3.5",
]

[project.optional-dependencies]
gui = [
    "numpy<2.0.0",
    "PySide6>=6.5.0",
    "pyqtgraph>=0.13.0",
    "qasync>=0.24.0",
]
[tool.setuptools]
packages = []

[tool.uv]
package = false
